[build]
  command = "chmod +x ./server/lib/yt-dlp && npm run postinstall && mkdir -p public"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "server"
  node_bundler = "esbuild"

[dev]
  command = "npm run start"