[build]
  command = "chmod +x ./server/lib/yt-dlp && npm run postinstall"
  publish = "public"

[build.environment]
  NODE_VERSION = "22.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "server"
  node_bundler = "esbuild"

[dev]
  command = "npm run start"