[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/songs"
healthcheckTimeout = 100
restartPolicy = "on-failure"

[[services]]
name = "web"
persistentStorage = "/data"