[build]
builder = "nixpacks"
buildCommand = "cd server && npm install"

[deploy]
startCommand = "node server/app.js"
healthcheckPath = "/api/songs"
healthcheckTimeout = 100
restartPolicy = "on-failure"

[[services]]
name = "web"
persistentStorage = "/data"