services:
  - type: web
    name: konnnmusic
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 curl ffmpeg
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./server/lib/yt-dlp
      chmod +x ./server/lib/yt-dlp
      chmod +x ./server/app.js
      mkdir -p /opt/render/project/tmp/public/{audios,infos}
      npm install
    startCommand: cd server && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: YTDLP_PATH
        value: ./server/lib/yt-dlp
      - key: STORAGE_DIR 
        value: /opt/render/project/tmp